[package]
name = "octo-init"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = "s"
strip = true
panic = "abort"
lto = "fat"
codegen-units = 1

[profile.minimal]
inherits = "release"
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.fast]
inherits = "release"
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"