[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-C", "target-feature=+crt-static", 
  "-C", "link-arg=-static",
  "-C", "link-arg=-no-pie",
  "-C", "relocation-model=static",

  "-C", "link-arg=-Wl,-z,norelro",
  "-C", "link-arg=-Wl,-z,nocopyreloc",
  "-C", "link-arg=-Wl,--build-id=none",
  "-C", "link-arg=-Wl,--gc-sections",

  "-C", "link-arg=-Wl,-z,max-page-size=0x1000",

  "-C", "panic=abort",
  "-C", "force-unwind-tables=no",

  "-C", "link-arg=-Wl,-s",
]